package com.mvoro.developer.springmvcrecipeproject.domain;

import java.math.BigDecimal;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Entity
public class Ingredient {

    /**
     * JPA requires no-args constructor for domain objects
     * because it often happens that the JPA provider has to instantiate your domain object dynamically.
     * It cannot do so, unless there is a no-arg constructor - it can't guess what the arguments should be.
     */
    public Ingredient() {

    }

    public Ingredient(String description, BigDecimal amount, UnitOfMeasure unitOfMeasure) {
        this.description = description;
        this.amount = amount;
        this.unitOfMeasure = unitOfMeasure;
    }

    // The primary key that will be autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String description;

    private BigDecimal amount;

    // No Cascade: We don't want to remove a UnitOfMeasure if we remove an Ingredient
    @ManyToOne
    private UnitOfMeasure unitOfMeasure;

    // Many ingredients for one Recipe. No cascade here because we don't want to remove a Recipe if we remove an ingredient
    @ManyToOne
    private Recipe recipe;

}
