package com.mvoro.developer.springmvcrecipeproject.domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;

@Entity
public class UnitOfMeasure {

    // The primary key that will be autogenerated
    @Id
    @GeneratedValue
    private Long id;

    @OneToOne
    private Ingredient ingredient;

    private String uof;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Ingredient getIngredient() {
        return ingredient;
    }

    public void setIngredient(Ingredient ingredient) {
        this.ingredient = ingredient;
    }

    public String getUof() {
        return uof;
    }

    public void setUof(String uof) {
        this.uof = uof;
    }
}
